apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: replicated-database
spec:
  project: default
  source:
    repoURL: https://github.com/TylerWon/replicated-database-k8s
    path: .
    targetRevision: HEAD
    directory:
      recurse: true
      exclude: 'argocd/**'
  destination:
    server: https://kubernetes.default.svc
    namespace: replicated-database
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
